// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Mmk-tme9qt3tvioedDCEoVUBh6SA0Tk',
    appId: '1:702970152564:web:b829b17b7492a493037321',
    messagingSenderId: '702970152564',
    projectId: 'alexandria-university-app',
    authDomain: 'alexandria-university-app.firebaseapp.com',
    databaseURL: 'https://alexandria-university-app-default-rtdb.firebaseio.com',
    storageBucket: 'alexandria-university-app.appspot.com',
    measurementId: 'G-4WDG9M7L47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9VF_JIowy25ybDzK4jJlxTG_OBVulrq0',
    appId: '1:702970152564:android:cfcefef23edf0acb037321',
    messagingSenderId: '702970152564',
    projectId: 'alexandria-university-app',
    databaseURL: 'https://alexandria-university-app-default-rtdb.firebaseio.com',
    storageBucket: 'alexandria-university-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLSJQqlSIj3vrivf7MNNyA-NUkFjeIzw',
    appId: '1:702970152564:ios:7987dd84af9282b2037321',
    messagingSenderId: '702970152564',
    projectId: 'alexandria-university-app',
    databaseURL: 'https://alexandria-university-app-default-rtdb.firebaseio.com',
    storageBucket: 'alexandria-university-app.appspot.com',
    androidClientId: '702970152564-7ue8j666f7f0b7kfna98i733u6esaevq.apps.googleusercontent.com',
    iosClientId: '702970152564-8l0613e1e0vrr86hb9s1qtlkqeu0rt5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.alexUniNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJLSJQqlSIj3vrivf7MNNyA-NUkFjeIzw',
    appId: '1:702970152564:ios:5402a9411531c661037321',
    messagingSenderId: '702970152564',
    projectId: 'alexandria-university-app',
    databaseURL: 'https://alexandria-university-app-default-rtdb.firebaseio.com',
    storageBucket: 'alexandria-university-app.appspot.com',
    androidClientId: '702970152564-7ue8j666f7f0b7kfna98i733u6esaevq.apps.googleusercontent.com',
    iosClientId: '702970152564-msic2t8ugvfklk8khvguhckgpr9orgr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.alexUniNew.RunnerTests',
  );
}
